### ISSUE TITLE
How to generate scss file?

### ISSUE THREAD

**Issue by SergeyShablenko** [jeerbl/webfonts-loader#24] opened 2017-07-18 10:47 UTC
I want to generate scss file with variables and shit, to use them inside my own scss, after svg built
I made 2 different configurations for webpack, first to compile svg to scss, second to compile project
Use case is to use generated with first task scss (which will contain variables with unicodes) and some styles, inside my own scss files

**Comment by jeerbl** [comment] 2017-07-22 21:39
Duplicate of #21.

**Closed by jeerbl** 2017-07-22 21:39 UTC
