### ISSUE TITLE
Please update README 

### ISSUE THREAD

**Issue by againstall** [jeerbl/webfonts-loader#25] opened 2017-07-21 22:18 UTC
Please update README with more examples of usage.
Build always break with:
`ERROR in ./~/css-loader!./~/webfonts-loader!./app/fontconfig.json
Module build failed:
 @ ./~/style-loader!./~/css-loader!./~/webfonts-loader!./app/fontconfig.json 4:14-121
 @ ./app/fontconfig.json
 @ ./app/index.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 ./app

ERROR in ./app/fontconfig.json
Module build failed: ModuleBuildError: Module build failed:
    at runLoaders (C:\Users\Alba\Desktop\projs\mashenka\node_modules\webpack\lib\NormalModule.js:192:19)
    at C:\Users\Alba\Desktop\projs\mashenka\node_modules\loader-runner\lib\LoaderRunner.js:364:11
    at C:\Users\Alba\Desktop\projs\mashenka\node_modules\loader-runner\lib\LoaderRunner.js:230:18
    at context.callback (C:\Users\Alba\Desktop\projs\mashenka\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
    at webfontsGenerator (C:\Users\Alba\Desktop\projs\mashenka\node_modules\webfonts-loader\index.js:166:14)
    at C:\Users\Alba\Desktop\projs\mashenka\node_modules\webfonts-generator\src\index.js:107:26
    at _rejected (C:\Users\Alba\Desktop\projs\mashenka\node_modules\q\q.js:864:24)
    at C:\Users\Alba\Desktop\projs\mashenka\node_modules\q\q.js:890:30
    at Promise.when (C:\Users\Alba\Desktop\projs\mashenka\node_modules\q\q.js:1142:31)
    at Promise.promise.promiseDispatch (C:\Users\Alba\Desktop\projs\mashenka\node_modules\q\q.js:808:41)
    at C:\Users\Alba\Desktop\projs\mashenka\node_modules\q\q.js:624:44
    at runSingle (C:\Users\Alba\Desktop\projs\mashenka\node_modules\q\q.js:137:13)
    at flush (C:\Users\Alba\Desktop\projs\mashenka\node_modules\q\q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
Child extract-text-webpack-plugin:

    ERROR in ./~/css-loader!./~/webfonts-loader!./app/fontconfig.json
    Module build failed:
     @ ./~/style-loader!./~/css-loader!./~/webfonts-loader!./app/fontconfig.json 4:14-121
webpack: Failed to compile.`

For config used json:
`{
  "files": [
    "./img/icons/search.svg"
  ],
  "fontName": "Awesomecons",
  "classPrefix": "ai-",
  "baseSelector": ".ai",
  "fixedWidth": true,
  "types": ["eot", "woff", "ttf", "svg"]
}`

**Comment by jeerbl** [comment] 2017-07-22 00:08
Closed as duplicate of #19. I'm working on it right now.

**Closed by jeerbl** 2017-07-22 00:08 UTC
